### PR TITLE
Yitsun feature

### PR DESCRIPTION
**Pull request by chentriangoes**
1. Database name is changed
2. All keywords "thought" are altered to "footprint"
3. Collections for "foorprints" and "users" are successfully created under the database for "memory-trust"

### CODE REVIEW

**Comment by chentriangoes** [comment]
1. A new data field for platform name is created
2. The onchange function for that new data field has to be removed

**Comment by chentriangoes** [comment]
Platform input is working properly

**Comment by chentriangoes** [comment]
1. Add logic to stop unregistered users from seeing footprints of others
2. Visitors have to log in to see footprints of others

**Comment by chentriangoes** [comment]
1. Only show platform name for the footprint list

**Comment by chentriangoes** [comment]
1. Add remove function codes
2. All are commented out at the moment

**Review by kishan254 — COMMENTED** [review]
done

**Pull request merged**
